# .goreleaser.yml
project_name: Deadpool # 定义项目名称，用于模板

before:
  hooks:
    # 确保 go mod tidy 在构建前运行
    - go mod tidy

builds:
  # 为每个目标平台/架构定义一个构建配置
  # Linux
  - id: linux-amd64
    main: ./main.go
    binary: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
  - id: linux-arm64
    main: ./main.go
    binary: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w

  # Windows
  - id: windows-amd64
    main: ./main.go
    binary: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
  - id: windows-arm64
    main: ./main.go
    binary: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - arm64
    ldflags:
      - -s -w

  # Darwin (macOS)
  - id: darwin-amd64
    main: ./main.go
    binary: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w
  - id: darwin-arm64
    main: ./main.go
    binary: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - arm64
    ldflags:
      - -s -w

archives:
  # Tar.gz 归档 (Linux & Darwin)
  - id: nix-archives
    # 通过 builds 字段引用上面定义的 build IDs
    builds:
      - linux-amd64
      - linux-arm64
      - darwin-amd64
      - darwin-arm64
    format: tar.gz
    # 归档文件名模板
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    # 包含在归档中的额外文件
    files:
      - README.md
      - LICENSE
      - config.toml

  # Zip 归档 (Windows)
  - id: win-archives
    # 通过 builds 字段引用上面定义的 build IDs
    builds:
      - windows-amd64
      - windows-arm64
    format: zip
    # 归档文件名模板
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    # 包含在归档中的额外文件
    files:
      - README.md
      - LICENSE
      - config.toml

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'Merge pull request'
      - 'Merge branch'

# release: # 发布相关的配置，通常使用默认值即可
#   draft: false
#   prerelease: auto