# .github/workflows/release.yml
name: GoReleaser

on:
  push:
    # 仅在推送 Git 标签时触发
    tags:
      - 'v*' # 匹配 v 开头的标签, 例如 v1.0.0, v2.1.3

permissions:
  contents: write # 需要写入权限来创建 Release 和上传构建产物

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # 获取所有历史记录，以便 GoReleaser 可以生成正确的 changelog
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          # 指定 Go 版本，建议与项目使用的版本一致或更新
          go-version: '1.21' # 或者使用 'stable' 获取最新稳定版
          # 启用缓存以加快后续构建速度
          cache: true

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5 # 使用官方的 GoReleaser Action
        with:
          # 指定 GoReleaser 版本 (可选, 默认使用最新版)
          # version: latest
          # 传递 goreleaser 命令的参数
          args: release --clean # --clean 会在构建前移除 dist 目录
        env:
          # GITHUB_TOKEN 是由 GitHub Actions 自动提供的，用于认证操作
          GITHUB_TOKEN: ${{ secrets.RELEASER_TOKEN }}
          # 如果你的 GoReleaser 配置需要其他环境变量，可以在这里添加
          # 例如： CGO_ENABLED: 0 # 也可以在这里设置 CGO_ENABLED